### PR TITLE
Use jsoniter instead of encoding/json

### PR DESCRIPTION
**Pull request by nkryuchkov**
WIP on https://github.com/SkycoinPro/skywire-services/issues/294

 Changes:	
- Use jsoniter instead of encoding/json

### CODE REVIEW

**Comment by taras-skycoin** [comment]
Everything looks good.

**Comment by jdknives** [comment]
@taras-skycoin you can merge if you tested this in integration env.

**Comment by taras-skycoin** [comment]
@jdknives I do not see a button. I think I need to be a collaborator of this repository to merge pull requests.

**Comment by Darkren** [comment]
@taras-skycoin @nkryuchkov this will panic on line 184 of `cmdutil/service_flags.go`. I've already tried that, `jsoniter` can't marshal using `\t` as identation character, should be replaced with spaces

**Comment by nkryuchkov** [comment]
@Darkren Thank you

**Review by taras-skycoin — APPROVED** [review]
I have just tested and the last commit does not panic.

**Pull request merged**
