### PR TITLE
dmsgcurl

### LINKED ISSUE #230: Reimplment curl-like features over dmsg
**Feature description**

We currently have two separate binaries for `dmsgget` and `dmsgpost`. There are a range of issues with the codebase itself, some of which are documented here: https://github.com/skycoin/dmsg/pull/228. 

There is also the larger issue, that we are duplicating a fair amount of code with having two separate binaries. It would be preferable to reimplement the functionality in a more versatile generic utility.

### PR DESCRIPTION
**Pull request by mrpalide**
Fixes #230 

 Changes:	
- remove `dmsgget` and `dmsgpost` app
- create `dmsgcurl` that is combine of `dmsgget` and `dmsgpost`

How to test this PR:
- build on this branch
- follow [`dmsgcurl`](https://raw.githubusercontent.com/mrpalide/dmsg/feat/dmsgcurl/docs/dmsgcurl.md) docs.

### CODE REVIEW

**Comment by mrpalide** [comment]
`skywire` work as well as by update dmsg on this PR:
https://github.com/skycoin/skywire/pull/1663

**Comment by mrpalide** [comment]
`skywire` work as well as by update dmsg on this PR: https://github.com/skycoin/skywire/pull/1663
`skywire-services` work as well as by update dmsg on this PR: https://github.com/skycoin/skywire-services/pull/31

**Review by jdknives — APPROVED** [review]
Looks good. How can I test the POST requests working? How did you test it?

**Review by jdknives — COMMENTED** [review]
Tested. Handled base case well enough. Will merge.

**Pull request merged**
